chore: bitrise with deploy

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -3,6 +3,8 @@ format_version: '3'
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 project_type: other
 trigger_map:
+- push_branch: master
+  workflow: deploy
 - push_branch: "*"
   workflow: primary
 - pull_request_source_branch: "*"
@@ -30,3 +32,33 @@ workflows:
         inputs:
         - command: test
     - deploy-to-bitrise-io@1.3.3: {}
+  deploy:
+    steps:
+    - script@1.1.4:
+        deps:
+          apt_get:
+          - name: python-pip
+          - name: python-dev
+          - name: build-essential
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # write your script here
+            mkdir $HOME/.aws
+            touch $HOME/.aws/config
+            chmod 600 $HOME/.aws/config
+            echo "[profile eb-cli]" > $HOME/.aws/config
+            echo "aws_access_key_id=$aws_access_key_id" >> $HOME/.aws/config
+            echo "aws_secret_access_key=$aws_secret_access_key" >> $HOME/.aws/config
+
+            sudo pip install --upgrade pip
+            sudo pip install awsebcli
+
+            eb deploy -v --debug Default-Environment
+    before_run:
+    - primary
